Repository NVIDIA/nv-ingest, pull requests merged in 2024-12, with the labels that each got.

#250 fix client example notebook
  client/client_examples/examples/python_client_usage.ipynb
Labels: bug, 24.12

#257 create milvus connection helpers
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#258 add upload and search functions
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#263 add requirements and final abstraction
  client/requirements.txt
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#268 add openai requirement for llama embeddings support
  client/requirements.txt
Labels: bug

#269 Milvus img resilience
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#272 Adjust all calls to handle_future_result to unpack result and trace_id
  client/src/nv_ingest_client/client/client.py
  client/src/nv_ingest_client/util/processing.py
Labels: bug

#275 add streaming milvus capability, output_fields param, and pin pacakges
  client/requirements.txt
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#278 Fix sparse embedding logic
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#281 Prop dim param
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#296 add milvus lite support using milvus uri file_path
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#303 Add cpu search to gpu index
  client/src/nv_ingest_client/util/milvus.py
  docker-compose.yaml
Labels: feature request
