Repository NVIDIA/nv-ingest, pull requests merged in 2025-05, with the labels that each got.

#699 Release notes for 25.04 and fix file types
  README.md
  docs/docs/extraction/overview.md
  docs/docs/extraction/releasenotes-nv-ingest.md
  docs/docs/extraction/telemetry.md
Labels: doc

#703 docs: Update Release Notes formatting
  docs/docs/extraction/releasenotes-nv-ingest.md
Labels: doc

#700 Indexes pymilvus update
  client/client_tests/util/test_milvus_util.py
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#679 Kubernetes MIG documentation
  helm/README.md
  helm/README.md.gotmpl
  helm/mig/nv-ingest-mig-config.yaml
Labels: doc

#694 Grpc embed
  api/api_tests/primitives/nim/model_interface/test_text_embedding.py
  api/src/nv_ingest_api/internal/primitives/nim/model_interface/text_embedding.py
  api/src/nv_ingest_api/internal/primitives/nim/nim_client.py
  client/src/nv_ingest_client/util/milvus.py
  client/src/nv_ingest_client/util/transport.py
Labels: feature request

#727 Add test for NIM client single vs multiple response grpc
  api/api_tests/primitives/nim/test_nim_client.py
  api/src/nv_ingest_api/internal/primitives/nim/nim_client.py
Labels: bug

#696 Treat json, md, and sh filetypes as text
  client/client_tests/client/test_interface.py
  client/src/nv_ingest_client/primitives/tasks/extract.py
  data/test.html
  data/test.json
  data/test.md
  data/test.sh
  data/test.txt
Labels: doc

#725 flatten all files from writer to bulk upload
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#748 Update library mode page code to use 25.4.2
  docs/docs/extraction/quickstart-library-mode.md
Labels: doc

#747 Update readme intro to use docs intro with full name
  README.md
  docs/docs/extraction/overview.md
Labels: doc

#755 Update readme intro to use docs intro with full name
  README.md
  docs/docs/extraction/overview.md
Labels: doc

#702 Fix milvus big
  client/client_tests/util/test_milvus_util.py
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#736 add ADT for vdb, change consistency level and fix bulk ingest
  client/client_tests/client/test_interface.py
  client/client_tests/util/test_milvus_util.py
  client/src/nv_ingest_client/client/interface.py
  client/src/nv_ingest_client/util/milvus.py
  client/src/nv_ingest_client/util/vdb/__init__.py
  client/src/nv_ingest_client/util/vdb/adt_vdb.py
  client/src/nv_ingest_client/util/vdb/milvus.py
Labels: bug, feature request

#774 docs: Miscellaneous bug fixes and improvements
  docs/docs/extraction/nemoretriever-parse.md
  docs/docs/extraction/quickstart-guide.md
  docs/docs/extraction/support-matrix.md
  docs/docs/extraction/troubleshoot.md
  docs/docs/overview.md
  docs/mkdocs.yml
Labels: doc

#788 Update Helm readme to clarify upgrade procedure
  helm/README.md
  helm/README.md.gotmpl
Labels: doc

#791 Add new notebooks to notebook page
  docs/docs/extraction/notebooks.md
Labels: doc

#789 Add new custom metadata page
  docs/docs/extraction/custom-metadata.md
  docs/mkdocs.yml
Labels: doc
