Repository NVIDIA/nv-ingest, pull requests merged in 2025-02, with the labels that each got.

#418 Fix broken links, table-fy environment variables
  README.md
  docs/docs/user-guide/developer-guide/environment-config.md
  docs/docs/user-guide/getting-started/quickstart-guide.md
Labels: doc

#433 add config to pull env vars into params
  client/src/nv_ingest_client/util/milvus.py
  client/src/nv_ingest_client/util/util.py
  tests/nv_ingest_client/util/test_util.py
Labels: feature request

#426 add sizing threshold detection for streaming instead of batch
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#438 instantiate client config schema
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#445 Rel Notes for 24.12.1 and miscellaneous bug fixes and updates
  CONTRIBUTING.md
  README.md
  docs/docs/user-guide/developer-guide/environment-config.md
  docs/docs/user-guide/developer-guide/ngc-api-key.md
  docs/docs/user-guide/index.md
  docs/docs/user-guide/prerequisites.md
  docs/docs/user-guide/quickstart-guide.md
  docs/docs/user-guide/releasenotes-nv-ingest.md
Labels: doc

#449 Add retrieval profile to docker compose up command
  README.md
  docs/docs/user-guide/quickstart-guide.md
Labels: doc

#451 Minor doc bug fixes
  docs/docs/user-guide/developer-guide/environment-config.md
  docs/docs/user-guide/quickstart-guide.md
Labels: doc

#467 Sphinx api docs build
  .github/workflows/build-docs.yml
  docs/sphinx_docs/source/conf.py
Labels: doc

#472 move sleep to only run when using bulk ingestion for milvus
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#475 fix to get all records from results in ingest_async for milvus
  client/src/nv_ingest_client/client/interface.py
Labels: bug

#476 match results from ingest and ingest-async
  client/src/nv_ingest_client/client/interface.py
  tests/nv_ingest_client/client/test_interface.py
Labels: feature request

#482 async results reverted to future
  client/src/nv_ingest_client/client/interface.py
  tests/nv_ingest_client/client/test_interface.py
Labels: feature request

#481 Update supported file types `docx`, `jpeg`, `pdf`, `png`, `pptx`, `svg`, `tiff`, `txt`
  README.md
  client/src/nv_ingest_client/nv_ingest_cli.py
  docs/docs/user-guide/developer-guide/nv-ingest_cli.md
  docs/docs/user-guide/index.md
Labels: doc

#381 add reranker to search
  client/src/nv_ingest_client/util/milvus.py
  client/src/nv_ingest_client/util/util.py
  docker-compose.yaml
  tests/nv_ingest_client/util/test_util.py
Labels: feature request

#495 Update Table of Contents, update metadata page, add name note, fix a few names and typos
  .devcontainer/README.md
  CONTRIBUTING.md
  README.md
  client/README.md
  docs/Makefile
  docs/docs/SUMMARY.md
  docs/docs/example_processed_docs/text/multimodal_test.pdf.metadata.json
  docs/docs/index.md
  docs/docs/user-guide/SUMMARY.md
  docs/docs/user-guide/content-metadata.md
  docs/docs/user-guide/contributing.md
  docs/docs/user-guide/deployment.md
  docs/docs/user-guide/developer-guide/SUMMARY.md
  docs/docs/user-guide/developer-guide/content-metadata.md
  docs/docs/user-guide/environment-config.md
  docs/docs/user-guide/kubernetes-dev.md
  docs/docs/user-guide/ngc-api-key.md
  docs/docs/user-guide/nv-ingest_cli.md
  docs/docs/user-guide/overview.md
  docs/docs/user-guide/prerequisites.md
  docs/docs/user-guide/quickstart-guide.md
  docs/docs/user-guide/releasenotes-nv-ingest.md
  docs/docs/user-guide/telemetry.md
  docs/mkdocs.yml
  examples/langchain_multimodal_rag.ipynb
  examples/llama_index_multimodal_rag.ipynb
  examples/store_and_display_images.ipynb
  helm/README.md
  skaffold/README.md
Labels: doc
