Repository NVIDIA/nv-ingest, pull requests merged in 2025-01, with the labels that each got.

#325 fixes to handle upgrades in milvus packages and fix for gpu-to-cpu in…
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#331 Fix some broken links and light editing in kubernetes.md
  docs/docs/user-guide/developer-guide/kubernetes-dev.md
Labels: doc

#333 add milvus logic to ingestor as psuedo task
  client/src/nv_ingest_client/client/interface.py
  client/src/nv_ingest_client/util/milvus.py
  tests/nv_ingest_client/client/test_interface.py
  tests/nv_ingest_client/util/test_milvus_util.py
Labels: feature request

#372 reverting adapt cpu logic to use GPU as default
  client/src/nv_ingest_client/util/milvus.py
Labels: bug

#347 adds 2.5.3 bm25 support while keeping previous support for milvus lite
  client/src/nv_ingest_client/util/milvus.py
  docker-compose.yaml
Labels: feature request

#396 add error check for embedding and text with logging
  client/src/nv_ingest_client/util/milvus.py
Labels: feature request

#397 Deleting docs-temp folder no longer needed
  docs-temp/content-metadata.md
  docs-temp/deployment.md
  docs-temp/dev/triton_models.md
  docs-temp/environment-config.md
  docs-temp/example_processed_docs/image/multimodal_test.pdf.metadata.json
  docs-temp/example_processed_docs/structured/multimodal_test.pdf.metadata.json
  docs-temp/example_processed_docs/text/multimodal_test.pdf.metadata.json
  docs-temp/images/doughnut_batch_dize.png
  docs-temp/images/generate_personal_key.png
  docs-temp/images/image_viewer_example.png
  docs-temp/images/prometheus.png
  docs-temp/images/test.pdf.png
  docs-temp/images/zipkin.png
  docs-temp/kubernetes-dev.md
  docs-temp/ngc-api-key.md
  docs-temp/nv-ingest_cli.md
  docs-temp/telemetry.md
Labels: doc
